---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/doctors/{doctor_id}/working_hours":
    parameters:
    - name: doctor_id
      in: path
      description: doctor_id
      required: true
      schema:
        type: string
    get:
      summary: list working_hours
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
